version: '3'

services:
  reverse-proxy:
    image: mattrob1nson/reverse-proxy
    build:
      context: ./build/reverse-proxy/
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx-net
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    volumes:
      - "./data/nginx-conf:/etc/nginx/conf.d"
      - "./data/nginx-vhost:/etc/nginx/vhost.d"
      - "./data/html:/usr/share/nginx/html"
      - "./data/certs:/etc/nginx/certs:ro"

  docker-gen:
    image: mattrob1nson/docker-gen
    build:
      context: ./build/reverse-proxy/
      dockerfile: ./Dockerfile
    restart: unless-stopped
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./data/nginx-conf:/etc/nginx/conf.d"
      - "./data/nginx-vhost:/etc/nginx/vhost.d"
      - "./data/html:/usr/share/nginx/html"
      - "./data/certs:/etc/nginx/certs:ro"

  letsencrypt:
    image: mattrob1nson/letsencrypt
    build:
      context: ./build/letsencrypt/
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./data/nginx-conf:/etc/nginx/conf.d"
      - "./data/nginx-vhost:/etc/nginx/vhost.d"
      - "./data/html:/usr/share/nginx/html"
      - "./data/certs:/etc/nginx/certs:rw"
    depends_on:
      - reverse-proxy

networks:
  nginx-net:
